### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by KAVASKAR95** [allangoing/apkshellext#61] opened 2016-10-15 08:04 UTC
Thanks... But Small bug: download a APK file from Mozilla Firefox....Automatically Download Canceled..(Sometimes) After Not Delete (0Bytes)APK File... :( ||| Part File Delete Successfully...

**Comment by MarMicMan** [comment] 2016-11-07 10:51
Same here. :-(

You can reproduce it:
- Install the extension
- Download first apk file from the internet -> all right
- Edit this apk file (e.g. renaming by the tool)
- Download the next apk file -> Download failed
- Now there are two files left download folder: xyz.apk and xyz.apk.part
- The deletion is only partially possible (only xyz.apk.part)

## \* Error message when deleting the xyz.apk file: fail to read file

Background:
- Download folder has full write access for everyone
- Error occurs with admintrator and normal user

Error also occurs when working normally (rename)
- in different folders
- with different files

It is not only the problem with download/Firefox.
I suspect, that access to files and folders are not properly "free".

System: Win7, 64bit
Browser: Firefox 49.0.2, 64bit
User: administrator

## 

Still something strange:
Sometimes the apk-file is automatically displayed again after "successful" deletion. So there seems to be no real deletion. :-(

**Comment by kkguo** [comment] 2017-03-16 15:52
I guess this is the same issue as #60 
one question, the xyz.apk is the first downloaded apk or the second one?
Looks like the file handler is not release in case of error happened.

**Comment by MarMicMan** [comment] 2017-03-20 10:25
Hi kkguo.

Thanks for replying.

I downloaded the last version and tried again.

The simplest way to reproduce the error is the following:
* Install the tool
* Download the first apk (the complete apk is downloaded)
* Download the next apk
    -> two files are created:
       (A) xyz.apk (file body with 0 KB)
       (B) xyz.apk.**part** (normal download behavior of Firefox)
    -> Firefox's download manager can not merge both files after successfully downloading the part file

The part file can be deleted, the body file (0 KB) can not be deleted!

The error has nothing to do with the apk file. It seems that the second action with the tool does not work.

**Comment by MarMicMan** [comment] 2017-03-20 10:33
> It seems that the second action with the tool does not work.

**Yes. Every second action/download does not work!**

**Comment by kkguo** [comment] 2019-06-11 14:54
close this now, reopen if problem persists

**Closed as completed by kkguo** 2019-06-11 14:54 UTC
Labels: bug, Accepted
