### ISSUE TITLE
Setup  msi/exe  -= make ApkShellExt2 as Installer =-

### ISSUE THREAD

**Issue by blackcrack** [allangoing/apkshellext#84] opened 2019-07-21 06:27 UTC
>_**issue a correckt installer programm for ApkShellExt2 or a Supporter who can and have a full Version of a MSI-Creator Programm where can support kkguo with his APKShellExt2 program in the next Years**_

Hi @kkguo ,

lil question about your Programming language, is this visualstudio ?

i have found there something ..
http://runlearning.blogspot.com/2014/12/how-to-creating-your-msi-installer.html

i be at search, so let this issue open up to exist an exe or msi-installer for your Program.

if there in the Space.. Internet Space anyone who can work or have a full version of WIX or an other msi-install creator program, please don't hold back, we need a correct installer for kkguo 's nice and helpful program,  so if you in able for supporting kkguo in a good msi-installer, please contact and give info.  

Thank you :)

best regards
Blacky

link collecting:
https://success.trendmicro.com/solution/1054112-creating-an-msi-package-to-install-the-client-server-security-agent-csa
https://resources.flexera.com/web/pdf/WhitePaper-IS-Designing-Update-Friendly-MSI-Installation.pdf
http://www.installsite.org/pages/en/msi/authoring.htm
https://www.codeproject.com/Articles/568476/Creating-an-MSI-Setup-Package-for-Csharp-Windows

**Comment by kkguo** [comment] 2019-07-31 19:05
Duplicate of #86 , closed

**Closed as completed by kkguo** 2019-07-31 19:05 UTC
Labels: feature-request
